DROP DATABASE dynamic_news;
CREATE DATABASE dynamic_news;
USE dynamic_news;

CREATE TABLE feedzilla(
	id INTEGER NOT NULL,
	title VARCHAR(200) NOT NULL,
  	source VARCHAR(200) NOT NULL,
  	source_url VARCHAR(200) NOT NULL,
  	summary VARCHAR(500) NOT NULL,
  	publish_date DATETIME NOT NULL,
  	url VARCHAR(200),
  	location VARCHAR(200),
  	tags VARCHAR(300),
  	latitude VARCHAR(200),
  	longitude VARCHAR(200),
	PRIMARY KEY (id),
	UNIQUE KEY (title)
);

CREATE TABLE twitter(
    tweet_id DOUBLE NOT NULL,
    news_id INTEGER NOT NULL,
    screen_name VARCHAR(50) NOT NULL,
    created_at DATETIME NOT NULL,
    hashtags VARCHAR(140) NOT NULL,
    location VARCHAR(200) NOT NULL,
    coordinates VARCHAR(200) NOT NULL,
    text VARCHAR(150) NOT NULL,
    follower_count INTEGER NOT NULL,
    PRIMARY KEY (tweet_id)
);

CREATE TABLE continents(
    continent VARCHAR(200) NOT NULL,
    PRIMARY KEY (continent)
);

INSERT INTO continents VALUES('Africa' );
INSERT INTO continents VALUES('Asia' );
INSERT INTO continents VALUES('Australia' );
INSERT INTO continents VALUES('Europe' );
INSERT INTO continents VALUES('North America' );
INSERT INTO continents VALUES('South America' );
INSERT INTO continents VALUES('Antarctica' );

CREATE TABLE countries(
	country	VARCHAR(200) NOT NULL,
	PRIMARY KEY (country)
);

INSERT INTO countries VALUES('Afghanistan' );
INSERT INTO countries VALUES('Albania' );
INSERT INTO countries VALUES('Algeria' );
INSERT INTO countries VALUES('Andorra' );
INSERT INTO countries VALUES('Angola' );
INSERT INTO countries VALUES('Antigua & Deps' );
INSERT INTO countries VALUES('Argentina' );
INSERT INTO countries VALUES('Armenia' );
INSERT INTO countries VALUES('Australia' );
INSERT INTO countries VALUES('Austria' );
INSERT INTO countries VALUES('Azerbaijan' );
INSERT INTO countries VALUES('Bahamas' );
INSERT INTO countries VALUES('Bahrain' );
INSERT INTO countries VALUES('Bangladesh' );
INSERT INTO countries VALUES('Barbados' );
INSERT INTO countries VALUES('Belarus' );
INSERT INTO countries VALUES('Belgium' );
INSERT INTO countries VALUES('Belize' );
INSERT INTO countries VALUES('Benin' );
INSERT INTO countries VALUES('Bhutan' );
INSERT INTO countries VALUES('Bolivia' );
INSERT INTO countries VALUES('Bosnia Herzegovina' );
INSERT INTO countries VALUES('Botswana' );
INSERT INTO countries VALUES('Brazil' );
INSERT INTO countries VALUES('Brunei' );
INSERT INTO countries VALUES('Bulgaria' );
INSERT INTO countries VALUES('Burkina' );
INSERT INTO countries VALUES('Burundi' );
INSERT INTO countries VALUES('Cambodia' );
INSERT INTO countries VALUES('Cameroon' );
INSERT INTO countries VALUES('Canada' );
INSERT INTO countries VALUES('Cape Verde' );
INSERT INTO countries VALUES('Central African Rep' );
INSERT INTO countries VALUES('Chad' );
INSERT INTO countries VALUES('Chile' );
INSERT INTO countries VALUES('China' );
INSERT INTO countries VALUES('Colombia' );
INSERT INTO countries VALUES('Comoros' );
INSERT INTO countries VALUES('Congo' );
INSERT INTO countries VALUES('Congo {Democratic Rep}' );
INSERT INTO countries VALUES('Costa Rica' );
INSERT INTO countries VALUES('Croatia' );
INSERT INTO countries VALUES('Cuba' );
INSERT INTO countries VALUES('Cyprus' );
INSERT INTO countries VALUES('Czech Republic' );
INSERT INTO countries VALUES('Denmark' );
INSERT INTO countries VALUES('Djibouti' );
INSERT INTO countries VALUES('Dominica' );
INSERT INTO countries VALUES('Dominican Republic' );
INSERT INTO countries VALUES('East Timor' );
INSERT INTO countries VALUES('Ecuador' );
INSERT INTO countries VALUES('Egypt' );
INSERT INTO countries VALUES('El Salvador' );
INSERT INTO countries VALUES('Equatorial Guinea' );
INSERT INTO countries VALUES('Eritrea' );
INSERT INTO countries VALUES('Estonia' );
INSERT INTO countries VALUES('Ethiopia' );
INSERT INTO countries VALUES('Fiji' );
INSERT INTO countries VALUES('Finland' );
INSERT INTO countries VALUES('France' );
INSERT INTO countries VALUES('Gabon' );
INSERT INTO countries VALUES('Gambia' );
INSERT INTO countries VALUES('Georgia' );
INSERT INTO countries VALUES('Germany' );
INSERT INTO countries VALUES('Ghana' );
INSERT INTO countries VALUES('Greece' );
INSERT INTO countries VALUES('Grenada' );
INSERT INTO countries VALUES('Guatemala' );
INSERT INTO countries VALUES('Guinea' );
INSERT INTO countries VALUES('Guinea-Bissau' );
INSERT INTO countries VALUES('Guyana' );
INSERT INTO countries VALUES('Haiti' );
INSERT INTO countries VALUES('Honduras' );
INSERT INTO countries VALUES('Hungary' );
INSERT INTO countries VALUES('Iceland' );
INSERT INTO countries VALUES('India' );
INSERT INTO countries VALUES('Indonesia' );
INSERT INTO countries VALUES('Iran' );
INSERT INTO countries VALUES('Iraq' );
INSERT INTO countries VALUES('Ireland' );
INSERT INTO countries VALUES('Israel' );
INSERT INTO countries VALUES('Italy' );
INSERT INTO countries VALUES('Ivory Coast' );
INSERT INTO countries VALUES('Jamaica' );
INSERT INTO countries VALUES('Japan' );
INSERT INTO countries VALUES('Jordan' );
INSERT INTO countries VALUES('Kazakhstan' );
INSERT INTO countries VALUES('Kenya' );
INSERT INTO countries VALUES('Kiribati' );
INSERT INTO countries VALUES('Korea North' );
INSERT INTO countries VALUES('Korea South' );
INSERT INTO countries VALUES('Kosovo' );
INSERT INTO countries VALUES('Kuwait' );
INSERT INTO countries VALUES('Kyrgyzstan' );
INSERT INTO countries VALUES('Laos' );
INSERT INTO countries VALUES('Latvia' );
INSERT INTO countries VALUES('Lebanon' );
INSERT INTO countries VALUES('Lesotho' );
INSERT INTO countries VALUES('Liberia' );
INSERT INTO countries VALUES('Libya' );
INSERT INTO countries VALUES('Liechtenstein' );
INSERT INTO countries VALUES('Lithuania' );
INSERT INTO countries VALUES('Luxembourg' );
INSERT INTO countries VALUES('Macedonia' );
INSERT INTO countries VALUES('Madagascar' );
INSERT INTO countries VALUES('Malawi' );
INSERT INTO countries VALUES('Malaysia' );
INSERT INTO countries VALUES('Maldives' );
INSERT INTO countries VALUES('Mali' );
INSERT INTO countries VALUES('Malta' );
INSERT INTO countries VALUES('Marshall Islands' );
INSERT INTO countries VALUES('Mauritania' );
INSERT INTO countries VALUES('Mauritius' );
INSERT INTO countries VALUES('Mexico' );
INSERT INTO countries VALUES('Micronesia' );
INSERT INTO countries VALUES('Moldova' );
INSERT INTO countries VALUES('Monaco' );
INSERT INTO countries VALUES('Mongolia' );
INSERT INTO countries VALUES('Montenegro' );
INSERT INTO countries VALUES('Morocco' );
INSERT INTO countries VALUES('Mozambique' );
INSERT INTO countries VALUES('"Myanmar {Burma}"' );
INSERT INTO countries VALUES('Namibia' );
INSERT INTO countries VALUES('Nauru' );
INSERT INTO countries VALUES('Nepal' );
INSERT INTO countries VALUES('Netherlands' );
INSERT INTO countries VALUES('New Zealand' );
INSERT INTO countries VALUES('Nicaragua' );
INSERT INTO countries VALUES('Niger' );
INSERT INTO countries VALUES('Nigeria' );
INSERT INTO countries VALUES('Norway' );
INSERT INTO countries VALUES('Oman' );
INSERT INTO countries VALUES('Pakistan' );
INSERT INTO countries VALUES('Palau' );
INSERT INTO countries VALUES('Panama' );
INSERT INTO countries VALUES('Papua New Guinea' );
INSERT INTO countries VALUES('Paraguay' );
INSERT INTO countries VALUES('Peru' );
INSERT INTO countries VALUES('Philippines' );
INSERT INTO countries VALUES('Poland' );
INSERT INTO countries VALUES('Portugal' );
INSERT INTO countries VALUES('Qatar' );
INSERT INTO countries VALUES('Romania' );
INSERT INTO countries VALUES('Russia' );
INSERT INTO countries VALUES('Russian Federation' );
INSERT INTO countries VALUES('Rwanda' );
INSERT INTO countries VALUES('St Kitts & Nevis' );
INSERT INTO countries VALUES('St Lucia' );
INSERT INTO countries VALUES('Saint Vincent & the Grenadines' );
INSERT INTO countries VALUES('Samoa' );
INSERT INTO countries VALUES('San Marino' );
INSERT INTO countries VALUES('Sao Tome & Principe' );
INSERT INTO countries VALUES('Saudi Arabia' );
INSERT INTO countries VALUES('Senegal' );
INSERT INTO countries VALUES('Serbia' );
INSERT INTO countries VALUES('Seychelles' );
INSERT INTO countries VALUES('Sierra Leone' );
INSERT INTO countries VALUES('Singapore' );
INSERT INTO countries VALUES('Slovakia' );
INSERT INTO countries VALUES('Slovenia' );
INSERT INTO countries VALUES('Solomon Islands' );
INSERT INTO countries VALUES('Somalia' );
INSERT INTO countries VALUES('South Africa' );
INSERT INTO countries VALUES('South Sudan' );
INSERT INTO countries VALUES('Spain' );
INSERT INTO countries VALUES('Sri Lanka' );
INSERT INTO countries VALUES('Sudan' );
INSERT INTO countries VALUES('Suriname' );
INSERT INTO countries VALUES('Swaziland' );
INSERT INTO countries VALUES('Sweden' );
INSERT INTO countries VALUES('Switzerland' );
INSERT INTO countries VALUES('Syria' );
INSERT INTO countries VALUES('Taiwan' );
INSERT INTO countries VALUES('Tajikistan' );
INSERT INTO countries VALUES('Tanzania' );
INSERT INTO countries VALUES('Thailand' );
INSERT INTO countries VALUES('Togo' );
INSERT INTO countries VALUES('Tonga' );
INSERT INTO countries VALUES('Trinidad & Tobago' );
INSERT INTO countries VALUES('Tunisia' );
INSERT INTO countries VALUES('Turkey' );
INSERT INTO countries VALUES('Turkmenistan' );
INSERT INTO countries VALUES('Tuvalu' );
INSERT INTO countries VALUES('Uganda' );
INSERT INTO countries VALUES('Ukraine' );
INSERT INTO countries VALUES('United Arab Emirates' );
INSERT INTO countries VALUES('United Kingdom' );
INSERT INTO countries VALUES('United States' );
INSERT INTO countries VALUES('Uruguay' );
INSERT INTO countries VALUES('Uzbekistan' );
INSERT INTO countries VALUES('Vanuatu' );
INSERT INTO countries VALUES('Vatican City' );
INSERT INTO countries VALUES('Venezuela' );
INSERT INTO countries VALUES('Vietnam' );
INSERT INTO countries VALUES('Yemen' );
INSERT INTO countries VALUES('Zambia' );
INSERT INTO countries VALUES('Zimbabwe' );



CREATE TABLE verbs(
	verb VARCHAR(200) NOT NULL,
	PRIMARY KEY (verb)
);

INSERT INTO verbs VALUES('abandon');
INSERT INTO verbs VALUES('abduct');
INSERT INTO verbs VALUES('ably');
INSERT INTO verbs VALUES('abolish');
INSERT INTO verbs VALUES('abscond');
INSERT INTO verbs VALUES('abuse');
INSERT INTO verbs VALUES('accelerate');
INSERT INTO verbs VALUES('accomplish');
INSERT INTO verbs VALUES('accuse');
INSERT INTO verbs VALUES('accrue');
INSERT INTO verbs VALUES('achieve');
INSERT INTO verbs VALUES('acquire');
INSERT INTO verbs VALUES('act');
INSERT INTO verbs VALUES('activate');
INSERT INTO verbs VALUES('actively');
INSERT INTO verbs VALUES('adapt');
INSERT INTO verbs VALUES('add');
INSERT INTO verbs VALUES('address');
INSERT INTO verbs VALUES('adeptly');
INSERT INTO verbs VALUES('adjust');
INSERT INTO verbs VALUES('administer');
INSERT INTO verbs VALUES('advance');
INSERT INTO verbs VALUES('advantageously');
INSERT INTO verbs VALUES('advise');
INSERT INTO verbs VALUES('advocate');
INSERT INTO verbs VALUES('affirm');
INSERT INTO verbs VALUES('aggressively');
INSERT INTO verbs VALUES('aid');
INSERT INTO verbs VALUES('aim');
INSERT INTO verbs VALUES('alert');
INSERT INTO verbs VALUES('allocate');
INSERT INTO verbs VALUES('ambitiously');
INSERT INTO verbs VALUES('analyze');
INSERT INTO verbs VALUES('answer');
INSERT INTO verbs VALUES('anticipate');
INSERT INTO verbs VALUES('apprehend');
INSERT INTO verbs VALUES('approach');
INSERT INTO verbs VALUES('appropriate');
INSERT INTO verbs VALUES('appropriately');
INSERT INTO verbs VALUES('arbitrate');
INSERT INTO verbs VALUES('arrange');
INSERT INTO verbs VALUES('arrest');
INSERT INTO verbs VALUES('artfully');
INSERT INTO verbs VALUES('ascertain');
INSERT INTO verbs VALUES('assault');
INSERT INTO verbs VALUES('assemble');
INSERT INTO verbs VALUES('assess');
INSERT INTO verbs VALUES('assign');
INSERT INTO verbs VALUES('assist');
INSERT INTO verbs VALUES('assure');
INSERT INTO verbs VALUES('attack');
INSERT INTO verbs VALUES('attain');
INSERT INTO verbs VALUES('attract');
INSERT INTO verbs VALUES('audit');
INSERT INTO verbs VALUES('augment');
INSERT INTO verbs VALUES('authenticate');
INSERT INTO verbs VALUES('author');
INSERT INTO verbs VALUES('authoritatively');
INSERT INTO verbs VALUES('authorize');
INSERT INTO verbs VALUES('automate');
INSERT INTO verbs VALUES('avert');
INSERT INTO verbs VALUES('avidly');
INSERT INTO verbs VALUES('avoid');
INSERT INTO verbs VALUES('award');
INSERT INTO verbs VALUES('balance');
INSERT INTO verbs VALUES('bang');
INSERT INTO verbs VALUES('bank');
INSERT INTO verbs VALUES('bar');
INSERT INTO verbs VALUES('beat');
INSERT INTO verbs VALUES('beneficially');
INSERT INTO verbs VALUES('berate');
INSERT INTO verbs VALUES('bill');
INSERT INTO verbs VALUES('bite');
INSERT INTO verbs VALUES('blast');
INSERT INTO verbs VALUES('blend');
INSERT INTO verbs VALUES('block');
INSERT INTO verbs VALUES('blow');
INSERT INTO verbs VALUES('bolster');
INSERT INTO verbs VALUES('book');
INSERT INTO verbs VALUES('boost');
INSERT INTO verbs VALUES('brace');
INSERT INTO verbs VALUES('brief');
INSERT INTO verbs VALUES('brighten');
INSERT INTO verbs VALUES('broke');
INSERT INTO verbs VALUES('buck');
INSERT INTO verbs VALUES('budget');
INSERT INTO verbs VALUES('built');
INSERT INTO verbs VALUES('bump');
INSERT INTO verbs VALUES('bury');
INSERT INTO verbs VALUES('bushwhack');
INSERT INTO verbs VALUES('calculate');
INSERT INTO verbs VALUES('call');
INSERT INTO verbs VALUES('calm');
INSERT INTO verbs VALUES('campaign');
INSERT INTO verbs VALUES('cancel');
INSERT INTO verbs VALUES('capably');
INSERT INTO verbs VALUES('capitalize');
INSERT INTO verbs VALUES('catch');
INSERT INTO verbs VALUES('centralize');
INSERT INTO verbs VALUES('certify');
INSERT INTO verbs VALUES('chair');
INSERT INTO verbs VALUES('challenge');
INSERT INTO verbs VALUES('champion');
INSERT INTO verbs VALUES('change');
INSERT INTO verbs VALUES('channel');
INSERT INTO verbs VALUES('charge');
INSERT INTO verbs VALUES('chart');
INSERT INTO verbs VALUES('chase');
INSERT INTO verbs VALUES('check');
INSERT INTO verbs VALUES('choke');
INSERT INTO verbs VALUES('circumscribe');
INSERT INTO verbs VALUES('circumvent');
INSERT INTO verbs VALUES('clap');
INSERT INTO verbs VALUES('clarify');
INSERT INTO verbs VALUES('clash');
INSERT INTO verbs VALUES('classify');
INSERT INTO verbs VALUES('climb');
INSERT INTO verbs VALUES('clip');
INSERT INTO verbs VALUES('clutch');
INSERT INTO verbs VALUES('coach');
INSERT INTO verbs VALUES('collaborate');
INSERT INTO verbs VALUES('collapse');
INSERT INTO verbs VALUES('collar');
INSERT INTO verbs VALUES('collate');
INSERT INTO verbs VALUES('collect');
INSERT INTO verbs VALUES('collide');
INSERT INTO verbs VALUES('combine');
INSERT INTO verbs VALUES('command');
INSERT INTO verbs VALUES('commandeer');
INSERT INTO verbs VALUES('communicate');
INSERT INTO verbs VALUES('competently');
INSERT INTO verbs VALUES('compile');
INSERT INTO verbs VALUES('complete');
INSERT INTO verbs VALUES('comply');
INSERT INTO verbs VALUES('compose');
INSERT INTO verbs VALUES('compute');
INSERT INTO verbs VALUES('conceive');
INSERT INTO verbs VALUES('conclusively');
INSERT INTO verbs VALUES('condense');
INSERT INTO verbs VALUES('conduct');
INSERT INTO verbs VALUES('confer');
INSERT INTO verbs VALUES('configure');
INSERT INTO verbs VALUES('conserve');
INSERT INTO verbs VALUES('consistently');
INSERT INTO verbs VALUES('consolidate');
INSERT INTO verbs VALUES('construct');
INSERT INTO verbs VALUES('consult');
INSERT INTO verbs VALUES('contract');
INSERT INTO verbs VALUES('control');
INSERT INTO verbs VALUES('conveniently');
INSERT INTO verbs VALUES('convert');
INSERT INTO verbs VALUES('coordinate');
INSERT INTO verbs VALUES('correlate');
INSERT INTO verbs VALUES('counsel');
INSERT INTO verbs VALUES('count');
INSERT INTO verbs VALUES('cram');
INSERT INTO verbs VALUES('crash');
INSERT INTO verbs VALUES('crawl');
INSERT INTO verbs VALUES('create');
INSERT INTO verbs VALUES('creep');
INSERT INTO verbs VALUES('cripple');
INSERT INTO verbs VALUES('critique');
INSERT INTO verbs VALUES('crouch');
INSERT INTO verbs VALUES('cultivate');
INSERT INTO verbs VALUES('cure');
INSERT INTO verbs VALUES('customize');
INSERT INTO verbs VALUES('cut');
INSERT INTO verbs VALUES('dance');
INSERT INTO verbs VALUES('dart');
INSERT INTO verbs VALUES('dash');
INSERT INTO verbs VALUES('deal');
INSERT INTO verbs VALUES('debate');
INSERT INTO verbs VALUES('decide');
INSERT INTO verbs VALUES('decidedly');
INSERT INTO verbs VALUES('decisively');
INSERT INTO verbs VALUES('deck');
INSERT INTO verbs VALUES('decorate');
INSERT INTO verbs VALUES('decrease');
INSERT INTO verbs VALUES('deduct');
INSERT INTO verbs VALUES('define');
INSERT INTO verbs VALUES('delegate');
INSERT INTO verbs VALUES('delete');
INSERT INTO verbs VALUES('deliberate');
INSERT INTO verbs VALUES('delineate');
INSERT INTO verbs VALUES('deliver');
INSERT INTO verbs VALUES('demonstrate');
INSERT INTO verbs VALUES('derive');
INSERT INTO verbs VALUES('descend');
INSERT INTO verbs VALUES('describe');
INSERT INTO verbs VALUES('design');
INSERT INTO verbs VALUES('detail');
INSERT INTO verbs VALUES('detect');
INSERT INTO verbs VALUES('determine');
INSERT INTO verbs VALUES('develop');
INSERT INTO verbs VALUES('devise');
INSERT INTO verbs VALUES('diagnose');
INSERT INTO verbs VALUES('dictate');
INSERT INTO verbs VALUES('dig');
INSERT INTO verbs VALUES('diligently');
INSERT INTO verbs VALUES('direct');
INSERT INTO verbs VALUES('discard');
INSERT INTO verbs VALUES('discover');
INSERT INTO verbs VALUES('dispatch');
INSERT INTO verbs VALUES('display');
INSERT INTO verbs VALUES('dissect');
INSERT INTO verbs VALUES('distinguish');
INSERT INTO verbs VALUES('distribute');
INSERT INTO verbs VALUES('ditch');
INSERT INTO verbs VALUES('dive');
INSERT INTO verbs VALUES('divert');
INSERT INTO verbs VALUES('do');
INSERT INTO verbs VALUES('dodge');
INSERT INTO verbs VALUES('dominate');
INSERT INTO verbs VALUES('dope');
INSERT INTO verbs VALUES('double');
INSERT INTO verbs VALUES('douse');
INSERT INTO verbs VALUES('draft');
INSERT INTO verbs VALUES('drag');
INSERT INTO verbs VALUES('drain');
INSERT INTO verbs VALUES('dramatize');
INSERT INTO verbs VALUES('drape');
INSERT INTO verbs VALUES('draw');
INSERT INTO verbs VALUES('dress');
INSERT INTO verbs VALUES('drill');
INSERT INTO verbs VALUES('drink');
INSERT INTO verbs VALUES('drip');
INSERT INTO verbs VALUES('drop');
INSERT INTO verbs VALUES('drown');
INSERT INTO verbs VALUES('drug');
INSERT INTO verbs VALUES('dry');
INSERT INTO verbs VALUES('duel');
INSERT INTO verbs VALUES('dunk');
INSERT INTO verbs VALUES('earn');
INSERT INTO verbs VALUES('ease');
INSERT INTO verbs VALUES('easily');
INSERT INTO verbs VALUES('edge');
INSERT INTO verbs VALUES('edit');
INSERT INTO verbs VALUES('educate');
INSERT INTO verbs VALUES('effect');
INSERT INTO verbs VALUES('effectively');
INSERT INTO verbs VALUES('effectually');
INSERT INTO verbs VALUES('efficiently');
INSERT INTO verbs VALUES('effortlessly');
INSERT INTO verbs VALUES('eject');
INSERT INTO verbs VALUES('elect');
INSERT INTO verbs VALUES('elevate');
INSERT INTO verbs VALUES('eliminate');
INSERT INTO verbs VALUES('elope');
INSERT INTO verbs VALUES('elude');
INSERT INTO verbs VALUES('emerge');
INSERT INTO verbs VALUES('employ');
INSERT INTO verbs VALUES('enable');
INSERT INTO verbs VALUES('enact');
INSERT INTO verbs VALUES('encourage');
INSERT INTO verbs VALUES('endure');
INSERT INTO verbs VALUES('engage');
INSERT INTO verbs VALUES('engineer');
INSERT INTO verbs VALUES('enjoin');
INSERT INTO verbs VALUES('ensnare');
INSERT INTO verbs VALUES('ensure');
INSERT INTO verbs VALUES('enter');
INSERT INTO verbs VALUES('equip');
INSERT INTO verbs VALUES('erupt');
INSERT INTO verbs VALUES('escalate');
INSERT INTO verbs VALUES('escape');
INSERT INTO verbs VALUES('establish');
INSERT INTO verbs VALUES('estimate');
INSERT INTO verbs VALUES('evacuate');
INSERT INTO verbs VALUES('evade');
INSERT INTO verbs VALUES('evaluate');
INSERT INTO verbs VALUES('evict');
INSERT INTO verbs VALUES('examine');
INSERT INTO verbs VALUES('execute');
INSERT INTO verbs VALUES('exert');
INSERT INTO verbs VALUES('exhale');
INSERT INTO verbs VALUES('exhibit');
INSERT INTO verbs VALUES('exit');
INSERT INTO verbs VALUES('expedite');
INSERT INTO verbs VALUES('expel');
INSERT INTO verbs VALUES('explode');
INSERT INTO verbs VALUES('experience');
INSERT INTO verbs VALUES('experiment');
INSERT INTO verbs VALUES('expertly');
INSERT INTO verbs VALUES('explain');
INSERT INTO verbs VALUES('explore');
INSERT INTO verbs VALUES('expose');
INSERT INTO verbs VALUES('extend');
INSERT INTO verbs VALUES('extirpate');
INSERT INTO verbs VALUES('extract');
INSERT INTO verbs VALUES('extricate');
INSERT INTO verbs VALUES('facilitate');
INSERT INTO verbs VALUES('fade');
INSERT INTO verbs VALUES('fake');
INSERT INTO verbs VALUES('fall');
INSERT INTO verbs VALUES('falter');
INSERT INTO verbs VALUES('fan');
INSERT INTO verbs VALUES('fashion');
INSERT INTO verbs VALUES('fast');
INSERT INTO verbs VALUES('faultlessly');
INSERT INTO verbs VALUES('favorably');
INSERT INTO verbs VALUES('fear');
INSERT INTO verbs VALUES('feed');
INSERT INTO verbs VALUES('feel');
INSERT INTO verbs VALUES('fend');
INSERT INTO verbs VALUES('field');
INSERT INTO verbs VALUES('fight');
INSERT INTO verbs VALUES('file');
INSERT INTO verbs VALUES('fill');
INSERT INTO verbs VALUES('finance');
INSERT INTO verbs VALUES('find');
INSERT INTO verbs VALUES('finger');
INSERT INTO verbs VALUES('finish');
INSERT INTO verbs VALUES('fix');
INSERT INTO verbs VALUES('flag');
INSERT INTO verbs VALUES('flap');
INSERT INTO verbs VALUES('flash');
INSERT INTO verbs VALUES('flatten');
INSERT INTO verbs VALUES('flaunt');
INSERT INTO verbs VALUES('flay');
INSERT INTO verbs VALUES('flee');
INSERT INTO verbs VALUES('flick');
INSERT INTO verbs VALUES('flinch');
INSERT INTO verbs VALUES('fling');
INSERT INTO verbs VALUES('flip');
INSERT INTO verbs VALUES('flit');
INSERT INTO verbs VALUES('float');
INSERT INTO verbs VALUES('flog');
INSERT INTO verbs VALUES('flounder');
INSERT INTO verbs VALUES('flout');
INSERT INTO verbs VALUES('flush');
INSERT INTO verbs VALUES('fly');
INSERT INTO verbs VALUES('focus');
INSERT INTO verbs VALUES('fondle');
INSERT INTO verbs VALUES('force');
INSERT INTO verbs VALUES('forecast');
INSERT INTO verbs VALUES('forge');
INSERT INTO verbs VALUES('formalize');
INSERT INTO verbs VALUES('form');
INSERT INTO verbs VALUES('formulate');
INSERT INTO verbs VALUES('fornicate');
INSERT INTO verbs VALUES('foster');
INSERT INTO verbs VALUES('found');
INSERT INTO verbs VALUES('fumble');
INSERT INTO verbs VALUES('functionally');
INSERT INTO verbs VALUES('fund');
INSERT INTO verbs VALUES('furnish');
INSERT INTO verbs VALUES('gain');
INSERT INTO verbs VALUES('gainfully');
INSERT INTO verbs VALUES('gallop');
INSERT INTO verbs VALUES('gather');
INSERT INTO verbs VALUES('generate');
INSERT INTO verbs VALUES('gesture');
INSERT INTO verbs VALUES('get');
INSERT INTO verbs VALUES('give');
INSERT INTO verbs VALUES('gnaw');
INSERT INTO verbs VALUES('gossip');
INSERT INTO verbs VALUES('gouge');
INSERT INTO verbs VALUES('govern');
INSERT INTO verbs VALUES('graduate');
INSERT INTO verbs VALUES('grab');
INSERT INTO verbs VALUES('grapple');
INSERT INTO verbs VALUES('grasp');
INSERT INTO verbs VALUES('greet');
INSERT INTO verbs VALUES('grind');
INSERT INTO verbs VALUES('grip');
INSERT INTO verbs VALUES('grope');
INSERT INTO verbs VALUES('ground');
INSERT INTO verbs VALUES('grow');
INSERT INTO verbs VALUES('growl');
INSERT INTO verbs VALUES('grunt');
INSERT INTO verbs VALUES('guard');
INSERT INTO verbs VALUES('guide');
INSERT INTO verbs VALUES('gyrate');
INSERT INTO verbs VALUES('hack');
INSERT INTO verbs VALUES('hail');
INSERT INTO verbs VALUES('halt');
INSERT INTO verbs VALUES('halve');
INSERT INTO verbs VALUES('hammer');
INSERT INTO verbs VALUES('handle');
INSERT INTO verbs VALUES('hang');
INSERT INTO verbs VALUES('harass');
INSERT INTO verbs VALUES('hasten');
INSERT INTO verbs VALUES('haul');
INSERT INTO verbs VALUES('head');
INSERT INTO verbs VALUES('help');
INSERT INTO verbs VALUES('hesitate');
INSERT INTO verbs VALUES('hide');
INSERT INTO verbs VALUES('hijack');
INSERT INTO verbs VALUES('hire');
INSERT INTO verbs VALUES('hit');
INSERT INTO verbs VALUES('hitch');
INSERT INTO verbs VALUES('hobble');
INSERT INTO verbs VALUES('hoist');
INSERT INTO verbs VALUES('hold');
INSERT INTO verbs VALUES('hover');
INSERT INTO verbs VALUES('hug');
INSERT INTO verbs VALUES('hurl');
INSERT INTO verbs VALUES('hurtle');
INSERT INTO verbs VALUES('hypothesize');
INSERT INTO verbs VALUES('identify');
INSERT INTO verbs VALUES('ignore');
INSERT INTO verbs VALUES('illustrate');
INSERT INTO verbs VALUES('imitate');
INSERT INTO verbs VALUES('implement');
INSERT INTO verbs VALUES('improve');
INSERT INTO verbs VALUES('improvise');
INSERT INTO verbs VALUES('inch');
INSERT INTO verbs VALUES('index');
INSERT INTO verbs VALUES('indict');
INSERT INTO verbs VALUES('individualize');
INSERT INTO verbs VALUES('induce');
INSERT INTO verbs VALUES('inflict');
INSERT INTO verbs VALUES('influence');
INSERT INTO verbs VALUES('inform');
INSERT INTO verbs VALUES('initiate');
INSERT INTO verbs VALUES('inject');
INSERT INTO verbs VALUES('injure');
INSERT INTO verbs VALUES('innovate');
INSERT INTO verbs VALUES('insert');
INSERT INTO verbs VALUES('inspect');
INSERT INTO verbs VALUES('inspire');
INSERT INTO verbs VALUES('install');
INSERT INTO verbs VALUES('instigate');
INSERT INTO verbs VALUES('institute');
INSERT INTO verbs VALUES('instruct');
INSERT INTO verbs VALUES('integrate');
INSERT INTO verbs VALUES('intensify');
INSERT INTO verbs VALUES('interchange');
INSERT INTO verbs VALUES('interpret');
INSERT INTO verbs VALUES('interview');
INSERT INTO verbs VALUES('introduce');
INSERT INTO verbs VALUES('invade');
INSERT INTO verbs VALUES('invent');
INSERT INTO verbs VALUES('inventory');
INSERT INTO verbs VALUES('invest');
INSERT INTO verbs VALUES('investigate');
INSERT INTO verbs VALUES('isolate');
INSERT INTO verbs VALUES('itemize');
INSERT INTO verbs VALUES('jab');
INSERT INTO verbs VALUES('jam');
INSERT INTO verbs VALUES('jar');
INSERT INTO verbs VALUES('jeer');
INSERT INTO verbs VALUES('jerk');
INSERT INTO verbs VALUES('jimmy');
INSERT INTO verbs VALUES('jingle');
INSERT INTO verbs VALUES('jolt');
INSERT INTO verbs VALUES('judge');
INSERT INTO verbs VALUES('jump');
INSERT INTO verbs VALUES('justify');
INSERT INTO verbs VALUES('keel');
INSERT INTO verbs VALUES('keynote');
INSERT INTO verbs VALUES('kibitz');
INSERT INTO verbs VALUES('kick');
INSERT INTO verbs VALUES('kidnap');
INSERT INTO verbs VALUES('kill');
INSERT INTO verbs VALUES('kneel');
INSERT INTO verbs VALUES('knife');
INSERT INTO verbs VALUES('land');
INSERT INTO verbs VALUES('lash');
INSERT INTO verbs VALUES('launch');
INSERT INTO verbs VALUES('lead');
INSERT INTO verbs VALUES('lean');
INSERT INTO verbs VALUES('leap');
INSERT INTO verbs VALUES('learn');
INSERT INTO verbs VALUES('lecture');
INSERT INTO verbs VALUES('led');
INSERT INTO verbs VALUES('left');
INSERT INTO verbs VALUES('lessen');
INSERT INTO verbs VALUES('level');
INSERT INTO verbs VALUES('license');
INSERT INTO verbs VALUES('lick');
INSERT INTO verbs VALUES('limp');
INSERT INTO verbs VALUES('link');
INSERT INTO verbs VALUES('listen');
INSERT INTO verbs VALUES('locate');
INSERT INTO verbs VALUES('log');
INSERT INTO verbs VALUES('lower');
INSERT INTO verbs VALUES('lunge');
INSERT INTO verbs VALUES('lurch');
INSERT INTO verbs VALUES('make');
INSERT INTO verbs VALUES('maim');
INSERT INTO verbs VALUES('maintain');
INSERT INTO verbs VALUES('manage');
INSERT INTO verbs VALUES('mangle');
INSERT INTO verbs VALUES('manipulate');
INSERT INTO verbs VALUES('manufacture');
INSERT INTO verbs VALUES('march');
INSERT INTO verbs VALUES('mark');
INSERT INTO verbs VALUES('market');
INSERT INTO verbs VALUES('massage');
INSERT INTO verbs VALUES('master');
INSERT INTO verbs VALUES('maul');
INSERT INTO verbs VALUES('measure');
INSERT INTO verbs VALUES('meddle');
INSERT INTO verbs VALUES('mediate');
INSERT INTO verbs VALUES('meet');
INSERT INTO verbs VALUES('mend');
INSERT INTO verbs VALUES('mentor');
INSERT INTO verbs VALUES('mimic');
INSERT INTO verbs VALUES('mingle');
INSERT INTO verbs VALUES('minimize');
INSERT INTO verbs VALUES('mobilize');
INSERT INTO verbs VALUES('mock');
INSERT INTO verbs VALUES('model');
INSERT INTO verbs VALUES('mold');
INSERT INTO verbs VALUES('molest');
INSERT INTO verbs VALUES('monitor');
INSERT INTO verbs VALUES('motivate');
INSERT INTO verbs VALUES('mourn');
INSERT INTO verbs VALUES('move');
INSERT INTO verbs VALUES('multiply');
INSERT INTO verbs VALUES('mumble');
INSERT INTO verbs VALUES('murder');
INSERT INTO verbs VALUES('muster');
INSERT INTO verbs VALUES('mutilate');
INSERT INTO verbs VALUES('nab');
INSERT INTO verbs VALUES('nag');
INSERT INTO verbs VALUES('nail');
INSERT INTO verbs VALUES('narrow');
INSERT INTO verbs VALUES('needle');
INSERT INTO verbs VALUES('negotiate');
INSERT INTO verbs VALUES('nick');
INSERT INTO verbs VALUES('nip');
INSERT INTO verbs VALUES('nominate');
INSERT INTO verbs VALUES('nurture');
INSERT INTO verbs VALUES('observe');
INSERT INTO verbs VALUES('obtain');
INSERT INTO verbs VALUES('occupy');
INSERT INTO verbs VALUES('offer');
INSERT INTO verbs VALUES('officiate');
INSERT INTO verbs VALUES('operate');
INSERT INTO verbs VALUES('order');
INSERT INTO verbs VALUES('organize');
INSERT INTO verbs VALUES('originate');
INSERT INTO verbs VALUES('outline');
INSERT INTO verbs VALUES('overcome');
INSERT INTO verbs VALUES('oversee');
INSERT INTO verbs VALUES('pack');
INSERT INTO verbs VALUES('participate');
INSERT INTO verbs VALUES('paddle');
INSERT INTO verbs VALUES('page');
INSERT INTO verbs VALUES('pander');
INSERT INTO verbs VALUES('panic');
INSERT INTO verbs VALUES('parachute');
INSERT INTO verbs VALUES('parade');
INSERT INTO verbs VALUES('paralyze');
INSERT INTO verbs VALUES('park');
INSERT INTO verbs VALUES('parry');
INSERT INTO verbs VALUES('party');
INSERT INTO verbs VALUES('pass');
INSERT INTO verbs VALUES('pat');
INSERT INTO verbs VALUES('patrol');
INSERT INTO verbs VALUES('pause');
INSERT INTO verbs VALUES('paw');
INSERT INTO verbs VALUES('peel');
INSERT INTO verbs VALUES('peep');
INSERT INTO verbs VALUES('penetrate');
INSERT INTO verbs VALUES('perceive');
INSERT INTO verbs VALUES('perfect');
INSERT INTO verbs VALUES('perform');
INSERT INTO verbs VALUES('persuade');
INSERT INTO verbs VALUES('photograph');
INSERT INTO verbs VALUES('pick');
INSERT INTO verbs VALUES('picket');
INSERT INTO verbs VALUES('pile');
INSERT INTO verbs VALUES('pilot');
INSERT INTO verbs VALUES('pin');
INSERT INTO verbs VALUES('pinch');
INSERT INTO verbs VALUES('pioneer');
INSERT INTO verbs VALUES('pirate');
INSERT INTO verbs VALUES('pitch');
INSERT INTO verbs VALUES('placate');
INSERT INTO verbs VALUES('place');
INSERT INTO verbs VALUES('plan');
INSERT INTO verbs VALUES('play');
INSERT INTO verbs VALUES('plod');
INSERT INTO verbs VALUES('plow');
INSERT INTO verbs VALUES('plunge');
INSERT INTO verbs VALUES('pocket');
INSERT INTO verbs VALUES('poke');
INSERT INTO verbs VALUES('polish');
INSERT INTO verbs VALUES('pore');
INSERT INTO verbs VALUES('pose');
INSERT INTO verbs VALUES('position');
INSERT INTO verbs VALUES('pounce');
INSERT INTO verbs VALUES('pout');
INSERT INTO verbs VALUES('pray');
INSERT INTO verbs VALUES('predict');
INSERT INTO verbs VALUES('preen');
INSERT INTO verbs VALUES('prepare');
INSERT INTO verbs VALUES('prescribe');
INSERT INTO verbs VALUES('present');
INSERT INTO verbs VALUES('primp');
INSERT INTO verbs VALUES('print');
INSERT INTO verbs VALUES('prioritize');
INSERT INTO verbs VALUES('probe');
INSERT INTO verbs VALUES('process');
INSERT INTO verbs VALUES('procure');
INSERT INTO verbs VALUES('prod');
INSERT INTO verbs VALUES('produce');
INSERT INTO verbs VALUES('profitable');
INSERT INTO verbs VALUES('program');
INSERT INTO verbs VALUES('project');
INSERT INTO verbs VALUES('promote');
INSERT INTO verbs VALUES('prompt');
INSERT INTO verbs VALUES('proofread');
INSERT INTO verbs VALUES('propel');
INSERT INTO verbs VALUES('propose');
INSERT INTO verbs VALUES('protect');
INSERT INTO verbs VALUES('prove');
INSERT INTO verbs VALUES('provide');
INSERT INTO verbs VALUES('provoke');
INSERT INTO verbs VALUES('pry');
INSERT INTO verbs VALUES('publicize');
INSERT INTO verbs VALUES('publish');
INSERT INTO verbs VALUES('pull');
INSERT INTO verbs VALUES('pummel');
INSERT INTO verbs VALUES('pump');
INSERT INTO verbs VALUES('punch');
INSERT INTO verbs VALUES('purchase');
INSERT INTO verbs VALUES('purge');
INSERT INTO verbs VALUES('pursue');
INSERT INTO verbs VALUES('push');
INSERT INTO verbs VALUES('qualify');
INSERT INTO verbs VALUES('question');
INSERT INTO verbs VALUES('quicken');
INSERT INTO verbs VALUES('quit');
INSERT INTO verbs VALUES('quiz');
INSERT INTO verbs VALUES('race');
INSERT INTO verbs VALUES('raid');
INSERT INTO verbs VALUES('raise');
INSERT INTO verbs VALUES('rally');
INSERT INTO verbs VALUES('ram');
INSERT INTO verbs VALUES('ransack');
INSERT INTO verbs VALUES('rape');
INSERT INTO verbs VALUES('rate');
INSERT INTO verbs VALUES('rattle');
INSERT INTO verbs VALUES('ravage');
INSERT INTO verbs VALUES('rave');
INSERT INTO verbs VALUES('read');
INSERT INTO verbs VALUES('realize');
INSERT INTO verbs VALUES('rebuild');
INSERT INTO verbs VALUES('receive');
INSERT INTO verbs VALUES('recline');
INSERT INTO verbs VALUES('recommend');
INSERT INTO verbs VALUES('reconcile');
INSERT INTO verbs VALUES('reconnoiter');
INSERT INTO verbs VALUES('record');
INSERT INTO verbs VALUES('recoup');
INSERT INTO verbs VALUES('recruit');
INSERT INTO verbs VALUES('redeem');
INSERT INTO verbs VALUES('reduce');
INSERT INTO verbs VALUES('reel');
INSERT INTO verbs VALUES('refer');
INSERT INTO verbs VALUES('regain');
INSERT INTO verbs VALUES('regulate');
INSERT INTO verbs VALUES('reinforce');
INSERT INTO verbs VALUES('rejoin');
INSERT INTO verbs VALUES('relax');
INSERT INTO verbs VALUES('relent');
INSERT INTO verbs VALUES('relentlessly');
INSERT INTO verbs VALUES('relieve');
INSERT INTO verbs VALUES('remove');
INSERT INTO verbs VALUES('render');
INSERT INTO verbs VALUES('renew');
INSERT INTO verbs VALUES('renovate');
INSERT INTO verbs VALUES('reorganize');
INSERT INTO verbs VALUES('repair');
INSERT INTO verbs VALUES('repel');
INSERT INTO verbs VALUES('report');
INSERT INTO verbs VALUES('represent');
INSERT INTO verbs VALUES('repulse');
INSERT INTO verbs VALUES('research');
INSERT INTO verbs VALUES('resign');
INSERT INTO verbs VALUES('resist');
INSERT INTO verbs VALUES('resolve');
INSERT INTO verbs VALUES('respond');
INSERT INTO verbs VALUES('restore');
INSERT INTO verbs VALUES('retain');
INSERT INTO verbs VALUES('retaliate');
INSERT INTO verbs VALUES('retreat');
INSERT INTO verbs VALUES('retrieve');
INSERT INTO verbs VALUES('reveal');
INSERT INTO verbs VALUES('review');
INSERT INTO verbs VALUES('revise');
INSERT INTO verbs VALUES('ride');
INSERT INTO verbs VALUES('rip');
INSERT INTO verbs VALUES('rise');
INSERT INTO verbs VALUES('risk');
INSERT INTO verbs VALUES('rob');
INSERT INTO verbs VALUES('rock');
INSERT INTO verbs VALUES('roll');
INSERT INTO verbs VALUES('rub');
INSERT INTO verbs VALUES('run');
INSERT INTO verbs VALUES('rush');
INSERT INTO verbs VALUES('sail');
INSERT INTO verbs VALUES('salute');
INSERT INTO verbs VALUES('sap');
INSERT INTO verbs VALUES('satisfy');
INSERT INTO verbs VALUES('save');
INSERT INTO verbs VALUES('saw');
INSERT INTO verbs VALUES('scale');
INSERT INTO verbs VALUES('scamper');
INSERT INTO verbs VALUES('scan');
INSERT INTO verbs VALUES('scare');
INSERT INTO verbs VALUES('scatter');
INSERT INTO verbs VALUES('scavenge');
INSERT INTO verbs VALUES('schedule');
INSERT INTO verbs VALUES('scold');
INSERT INTO verbs VALUES('scoop');
INSERT INTO verbs VALUES('scoot');
INSERT INTO verbs VALUES('score');
INSERT INTO verbs VALUES('scour');
INSERT INTO verbs VALUES('scout');
INSERT INTO verbs VALUES('scrape');
INSERT INTO verbs VALUES('scrawl');
INSERT INTO verbs VALUES('scream');
INSERT INTO verbs VALUES('screen');
INSERT INTO verbs VALUES('screw');
INSERT INTO verbs VALUES('scrub');
INSERT INTO verbs VALUES('scruff');
INSERT INTO verbs VALUES('scuffle');
INSERT INTO verbs VALUES('sculpt');
INSERT INTO verbs VALUES('scuttle');
INSERT INTO verbs VALUES('seal');
INSERT INTO verbs VALUES('search');
INSERT INTO verbs VALUES('secure');
INSERT INTO verbs VALUES('seduce');
INSERT INTO verbs VALUES('segment');
INSERT INTO verbs VALUES('seize');
INSERT INTO verbs VALUES('select');
INSERT INTO verbs VALUES('sell');
INSERT INTO verbs VALUES('sense');
INSERT INTO verbs VALUES('serve');
INSERT INTO verbs VALUES('service');
INSERT INTO verbs VALUES('set');
INSERT INTO verbs VALUES('set up');
INSERT INTO verbs VALUES('sever');
INSERT INTO verbs VALUES('sew');
INSERT INTO verbs VALUES('shake');
INSERT INTO verbs VALUES('shanghai');
INSERT INTO verbs VALUES('shape');
INSERT INTO verbs VALUES('share');
INSERT INTO verbs VALUES('sharpen');
INSERT INTO verbs VALUES('shave');
INSERT INTO verbs VALUES('shear');
INSERT INTO verbs VALUES('shell');
INSERT INTO verbs VALUES('shield');
INSERT INTO verbs VALUES('shift');
INSERT INTO verbs VALUES('shiver');
INSERT INTO verbs VALUES('shock');
INSERT INTO verbs VALUES('shoot');
INSERT INTO verbs VALUES('shorten');
INSERT INTO verbs VALUES('shout');
INSERT INTO verbs VALUES('shove');
INSERT INTO verbs VALUES('shovel');
INSERT INTO verbs VALUES('show');
INSERT INTO verbs VALUES('shun');
INSERT INTO verbs VALUES('shut');
INSERT INTO verbs VALUES('sidestep');
INSERT INTO verbs VALUES('sigh');
INSERT INTO verbs VALUES('signal');
INSERT INTO verbs VALUES('simplify');
INSERT INTO verbs VALUES('sip');
INSERT INTO verbs VALUES('sit');
INSERT INTO verbs VALUES('size');
INSERT INTO verbs VALUES('skid');
INSERT INTO verbs VALUES('skim');
INSERT INTO verbs VALUES('skip');
INSERT INTO verbs VALUES('skirt');
INSERT INTO verbs VALUES('slacken');
INSERT INTO verbs VALUES('slam');
INSERT INTO verbs VALUES('slap');
INSERT INTO verbs VALUES('slash');
INSERT INTO verbs VALUES('slay');
INSERT INTO verbs VALUES('slide');
INSERT INTO verbs VALUES('slug');
INSERT INTO verbs VALUES('smack');
INSERT INTO verbs VALUES('smear');
INSERT INTO verbs VALUES('smell');
INSERT INTO verbs VALUES('smuggle');
INSERT INTO verbs VALUES('snap');
INSERT INTO verbs VALUES('snare');
INSERT INTO verbs VALUES('snarl');
INSERT INTO verbs VALUES('snatch');
INSERT INTO verbs VALUES('snicker');
INSERT INTO verbs VALUES('sniff');
INSERT INTO verbs VALUES('snitch');
INSERT INTO verbs VALUES('snoop');
INSERT INTO verbs VALUES('snub');
INSERT INTO verbs VALUES('snuff');
INSERT INTO verbs VALUES('snuggle');
INSERT INTO verbs VALUES('soak');
INSERT INTO verbs VALUES('sock');
INSERT INTO verbs VALUES('soil');
INSERT INTO verbs VALUES('Sold');
INSERT INTO verbs VALUES('solve');
INSERT INTO verbs VALUES('sort');
INSERT INTO verbs VALUES('spark');
INSERT INTO verbs VALUES('spear');
INSERT INTO verbs VALUES('spell');
INSERT INTO verbs VALUES('spike');
INSERT INTO verbs VALUES('spin');
INSERT INTO verbs VALUES('splatter');
INSERT INTO verbs VALUES('splice');
INSERT INTO verbs VALUES('split');
INSERT INTO verbs VALUES('spot');
INSERT INTO verbs VALUES('spray');
INSERT INTO verbs VALUES('spread');
INSERT INTO verbs VALUES('spring');
INSERT INTO verbs VALUES('sprint');
INSERT INTO verbs VALUES('spurn');
INSERT INTO verbs VALUES('spy');
INSERT INTO verbs VALUES('squeak');
INSERT INTO verbs VALUES('stack');
INSERT INTO verbs VALUES('staff');
INSERT INTO verbs VALUES('stagger');
INSERT INTO verbs VALUES('stamp');
INSERT INTO verbs VALUES('stand');
INSERT INTO verbs VALUES('start');
INSERT INTO verbs VALUES('startle');
INSERT INTO verbs VALUES('steal');
INSERT INTO verbs VALUES('steer');
INSERT INTO verbs VALUES('step');
INSERT INTO verbs VALUES('stick');
INSERT INTO verbs VALUES('stiffen');
INSERT INTO verbs VALUES('stifle');
INSERT INTO verbs VALUES('stimulate');
INSERT INTO verbs VALUES('stock');
INSERT INTO verbs VALUES('stomp');
INSERT INTO verbs VALUES('stop');
INSERT INTO verbs VALUES('strangle');
INSERT INTO verbs VALUES('strap');
INSERT INTO verbs VALUES('strategize');
INSERT INTO verbs VALUES('streamline');
INSERT INTO verbs VALUES('strengthen');
INSERT INTO verbs VALUES('stress');
INSERT INTO verbs VALUES('strike');
INSERT INTO verbs VALUES('strip');
INSERT INTO verbs VALUES('stroke');
INSERT INTO verbs VALUES('struck');
INSERT INTO verbs VALUES('structure');
INSERT INTO verbs VALUES('stub');
INSERT INTO verbs VALUES('study');
INSERT INTO verbs VALUES('stuff');
INSERT INTO verbs VALUES('stumble');
INSERT INTO verbs VALUES('stun');
INSERT INTO verbs VALUES('subdue');
INSERT INTO verbs VALUES('submerge');
INSERT INTO verbs VALUES('succeed');
INSERT INTO verbs VALUES('suck');
INSERT INTO verbs VALUES('summarize');
INSERT INTO verbs VALUES('sum');
INSERT INTO verbs VALUES('summon');
INSERT INTO verbs VALUES('supervise');
INSERT INTO verbs VALUES('supply');
INSERT INTO verbs VALUES('support');
INSERT INTO verbs VALUES('surrender');
INSERT INTO verbs VALUES('survey');
INSERT INTO verbs VALUES('suspend');
INSERT INTO verbs VALUES('sustain');
INSERT INTO verbs VALUES('swagger');
INSERT INTO verbs VALUES('swallow');
INSERT INTO verbs VALUES('swap');
INSERT INTO verbs VALUES('sway');
INSERT INTO verbs VALUES('swear');
INSERT INTO verbs VALUES('swerve');
INSERT INTO verbs VALUES('swim');
INSERT INTO verbs VALUES('swing');
INSERT INTO verbs VALUES('swipe');
INSERT INTO verbs VALUES('switch');
INSERT INTO verbs VALUES('synergize');
INSERT INTO verbs VALUES('synthesize');
INSERT INTO verbs VALUES('systematize');
INSERT INTO verbs VALUES('tabulate');
INSERT INTO verbs VALUES('tackle');
INSERT INTO verbs VALUES('take');
INSERT INTO verbs VALUES('tap');
INSERT INTO verbs VALUES('target');
INSERT INTO verbs VALUES('taste');
INSERT INTO verbs VALUES('taunt');
INSERT INTO verbs VALUES('teach');
INSERT INTO verbs VALUES('tear');
INSERT INTO verbs VALUES('tease');
INSERT INTO verbs VALUES('telephone');
INSERT INTO verbs VALUES('terrorize');
INSERT INTO verbs VALUES('test');
INSERT INTO verbs VALUES('thin');
INSERT INTO verbs VALUES('thrash');
INSERT INTO verbs VALUES('thread');
INSERT INTO verbs VALUES('threaten');
INSERT INTO verbs VALUES('throw');
INSERT INTO verbs VALUES('tickle');
INSERT INTO verbs VALUES('tie');
INSERT INTO verbs VALUES('tighten');
INSERT INTO verbs VALUES('tilt');
INSERT INTO verbs VALUES('tip');
INSERT INTO verbs VALUES('toss');
INSERT INTO verbs VALUES('touch');
INSERT INTO verbs VALUES('tout');
INSERT INTO verbs VALUES('track');
INSERT INTO verbs VALUES('train');
INSERT INTO verbs VALUES('transcribe');
INSERT INTO verbs VALUES('transform');
INSERT INTO verbs VALUES('translate');
INSERT INTO verbs VALUES('transport');
INSERT INTO verbs VALUES('trap');
INSERT INTO verbs VALUES('tread');
INSERT INTO verbs VALUES('treat');
INSERT INTO verbs VALUES('trim');
INSERT INTO verbs VALUES('trip');
INSERT INTO verbs VALUES('triple');
INSERT INTO verbs VALUES('trot');
INSERT INTO verbs VALUES('trounce');
INSERT INTO verbs VALUES('try');
INSERT INTO verbs VALUES('tuck');
INSERT INTO verbs VALUES('tug');
INSERT INTO verbs VALUES('tumble');
INSERT INTO verbs VALUES('turn');
INSERT INTO verbs VALUES('tutor');
INSERT INTO verbs VALUES('twist');
INSERT INTO verbs VALUES('type');
INSERT INTO verbs VALUES('uncover');
INSERT INTO verbs VALUES('understand');
INSERT INTO verbs VALUES('undertake');
INSERT INTO verbs VALUES('undo');
INSERT INTO verbs VALUES('undress');
INSERT INTO verbs VALUES('unfold');
INSERT INTO verbs VALUES('unify');
INSERT INTO verbs VALUES('uniformly');
INSERT INTO verbs VALUES('unite');
INSERT INTO verbs VALUES('unravel');
INSERT INTO verbs VALUES('untangle');
INSERT INTO verbs VALUES('unwind');
INSERT INTO verbs VALUES('update');
INSERT INTO verbs VALUES('usefully');
INSERT INTO verbs VALUES('usher');
INSERT INTO verbs VALUES('vacate');
INSERT INTO verbs VALUES('validate');
INSERT INTO verbs VALUES('value');
INSERT INTO verbs VALUES('vanish');
INSERT INTO verbs VALUES('vanquish');
INSERT INTO verbs VALUES('vault');
INSERT INTO verbs VALUES('vent');
INSERT INTO verbs VALUES('verbalize');
INSERT INTO verbs VALUES('verify');
INSERT INTO verbs VALUES('violate');
INSERT INTO verbs VALUES('wade');
INSERT INTO verbs VALUES('walk');
INSERT INTO verbs VALUES('wander');
INSERT INTO verbs VALUES('ward');
INSERT INTO verbs VALUES('watch');
INSERT INTO verbs VALUES('wave');
INSERT INTO verbs VALUES('wedge');
INSERT INTO verbs VALUES('weed');
INSERT INTO verbs VALUES('weigh');
INSERT INTO verbs VALUES('whack');
INSERT INTO verbs VALUES('whip');
INSERT INTO verbs VALUES('whirl');
INSERT INTO verbs VALUES('whistle');
INSERT INTO verbs VALUES('widen');
INSERT INTO verbs VALUES('wield');
INSERT INTO verbs VALUES('wiggle');
INSERT INTO verbs VALUES('win');
INSERT INTO verbs VALUES('work');
INSERT INTO verbs VALUES('wreck');
INSERT INTO verbs VALUES('wrench');
INSERT INTO verbs VALUES('wrestle');
INSERT INTO verbs VALUES('write');
INSERT INTO verbs VALUES('wrought');
INSERT INTO verbs VALUES('yank');
INSERT INTO verbs VALUES('yell');
INSERT INTO verbs VALUES('yelp');
INSERT INTO verbs VALUES('yield');
INSERT INTO verbs VALUES('zap');
INSERT INTO verbs VALUES('zip');


CREATE TABLE conjunctions(
	conjunction	VARCHAR(200) NOT NULL,
	PRIMARY KEY (conjunction)
);
INSERT INTO conjunctions VALUES('and');
INSERT INTO conjunctions VALUES('that');
INSERT INTO conjunctions VALUES('but');
INSERT INTO conjunctions VALUES('or');
INSERT INTO conjunctions VALUES('as');
INSERT INTO conjunctions VALUES('if');
INSERT INTO conjunctions VALUES('when');
INSERT INTO conjunctions VALUES('than');
INSERT INTO conjunctions VALUES('because');
INSERT INTO conjunctions VALUES('while');
INSERT INTO conjunctions VALUES('where');
INSERT INTO conjunctions VALUES('after');
INSERT INTO conjunctions VALUES('so');
INSERT INTO conjunctions VALUES('though');
INSERT INTO conjunctions VALUES('since');
INSERT INTO conjunctions VALUES('until');
INSERT INTO conjunctions VALUES('whether');
INSERT INTO conjunctions VALUES('before');
INSERT INTO conjunctions VALUES('although');
INSERT INTO conjunctions VALUES('nor');
INSERT INTO conjunctions VALUES('like');
INSERT INTO conjunctions VALUES('once');
INSERT INTO conjunctions VALUES('unless');
INSERT INTO conjunctions VALUES('now');
INSERT INTO conjunctions VALUES('except');

CREATE TABLE articles_adjs(
	article VARCHAR(200) NOT NULL,
	PRIMARY KEY (article)
);

INSERT INTO articles_adjs VALUES('a');
INSERT INTO articles_adjs VALUES('an');
INSERT INTO articles_adjs VALUES('the');


CREATE TABLE prepositions(
    preposition VARCHAR(200) NOT NULL,
    PRIMARY KEY (preposition)
);

INSERT INTO prepositions VALUES('aboard');
INSERT INTO prepositions VALUES('about');
INSERT INTO prepositions VALUES('above');
INSERT INTO prepositions VALUES('across');
INSERT INTO prepositions VALUES('after');
INSERT INTO prepositions VALUES('against');
INSERT INTO prepositions VALUES('along');
INSERT INTO prepositions VALUES('amid');
INSERT INTO prepositions VALUES('among');
INSERT INTO prepositions VALUES('anti');
INSERT INTO prepositions VALUES('around');
INSERT INTO prepositions VALUES('as');
INSERT INTO prepositions VALUES('at');
INSERT INTO prepositions VALUES('before');
INSERT INTO prepositions VALUES('behind');
INSERT INTO prepositions VALUES('below');
INSERT INTO prepositions VALUES('beneath');
INSERT INTO prepositions VALUES('beside');
INSERT INTO prepositions VALUES('besides');
INSERT INTO prepositions VALUES('between');
INSERT INTO prepositions VALUES('beyond');
INSERT INTO prepositions VALUES('but');
INSERT INTO prepositions VALUES('by');
INSERT INTO prepositions VALUES('concerning');
INSERT INTO prepositions VALUES('considering');
INSERT INTO prepositions VALUES('despite');
INSERT INTO prepositions VALUES('down');
INSERT INTO prepositions VALUES('during');
INSERT INTO prepositions VALUES('except');
INSERT INTO prepositions VALUES('excepting');
INSERT INTO prepositions VALUES('excluding');
INSERT INTO prepositions VALUES('following');
INSERT INTO prepositions VALUES('for');
INSERT INTO prepositions VALUES('from');
INSERT INTO prepositions VALUES('in');
INSERT INTO prepositions VALUES('inside');
INSERT INTO prepositions VALUES('into');
INSERT INTO prepositions VALUES('like');
INSERT INTO prepositions VALUES('minus');
INSERT INTO prepositions VALUES('near');
INSERT INTO prepositions VALUES('of');
INSERT INTO prepositions VALUES('off');
INSERT INTO prepositions VALUES('on');
INSERT INTO prepositions VALUES('onto');
INSERT INTO prepositions VALUES('opposite');
INSERT INTO prepositions VALUES('outside');
INSERT INTO prepositions VALUES('over');
INSERT INTO prepositions VALUES('past');
INSERT INTO prepositions VALUES('per');
INSERT INTO prepositions VALUES('plus');
INSERT INTO prepositions VALUES('regarding');
INSERT INTO prepositions VALUES('round');
INSERT INTO prepositions VALUES('save');
INSERT INTO prepositions VALUES('since');
INSERT INTO prepositions VALUES('than');
INSERT INTO prepositions VALUES('through');
INSERT INTO prepositions VALUES('to');
INSERT INTO prepositions VALUES('toward');
INSERT INTO prepositions VALUES('towards');
INSERT INTO prepositions VALUES('under');
INSERT INTO prepositions VALUES('underneath');
INSERT INTO prepositions VALUES('unlike');
INSERT INTO prepositions VALUES('until');
INSERT INTO prepositions VALUES('up');
INSERT INTO prepositions VALUES('upon');
INSERT INTO prepositions VALUES('versus');
INSERT INTO prepositions VALUES('via');
INSERT INTO prepositions VALUES('with');
INSERT INTO prepositions VALUES('within');
INSERT INTO prepositions VALUES('without');

CREATE TABLE pronouns(
	pronoun VARCHAR(200) NOT NULL,
	PRIMARY KEY (pronoun)
);

INSERT INTO pronouns VALUES('all');
INSERT INTO pronouns VALUES('another');
INSERT INTO pronouns VALUES('any');
INSERT INTO pronouns VALUES('anybody');
INSERT INTO pronouns VALUES('anyone');
INSERT INTO pronouns VALUES('anything');
INSERT INTO pronouns VALUES('both');
INSERT INTO pronouns VALUES('each');
INSERT INTO pronouns VALUES('eachother');
INSERT INTO pronouns VALUES('either');
INSERT INTO pronouns VALUES('everybody');
INSERT INTO pronouns VALUES('everyone');
INSERT INTO pronouns VALUES('everything');
INSERT INTO pronouns VALUES('few');
INSERT INTO pronouns VALUES('he');
INSERT INTO pronouns VALUES('her');
INSERT INTO pronouns VALUES('hers');
INSERT INTO pronouns VALUES('herself');
INSERT INTO pronouns VALUES('him');
INSERT INTO pronouns VALUES('himself');
INSERT INTO pronouns VALUES('his');
INSERT INTO pronouns VALUES('I');
INSERT INTO pronouns VALUES('it');
INSERT INTO pronouns VALUES('its');
INSERT INTO pronouns VALUES('itself');
INSERT INTO pronouns VALUES('little');
INSERT INTO pronouns VALUES('many');
INSERT INTO pronouns VALUES('me');
INSERT INTO pronouns VALUES('mine');
INSERT INTO pronouns VALUES('more');
INSERT INTO pronouns VALUES('most');
INSERT INTO pronouns VALUES('much');
INSERT INTO pronouns VALUES('my');
INSERT INTO pronouns VALUES('myself');
INSERT INTO pronouns VALUES('neither');
INSERT INTO pronouns VALUES('noone');
INSERT INTO pronouns VALUES('nobody');
INSERT INTO pronouns VALUES('none');
INSERT INTO pronouns VALUES('nothing');
INSERT INTO pronouns VALUES('one');
INSERT INTO pronouns VALUES('oneanother');
INSERT INTO pronouns VALUES('other');
INSERT INTO pronouns VALUES('others');
INSERT INTO pronouns VALUES('our');
INSERT INTO pronouns VALUES('ours');
INSERT INTO pronouns VALUES('ourselves');
INSERT INTO pronouns VALUES('several');
INSERT INTO pronouns VALUES('she');
INSERT INTO pronouns VALUES('some');
INSERT INTO pronouns VALUES('somebody');
INSERT INTO pronouns VALUES('someone');
INSERT INTO pronouns VALUES('something');
INSERT INTO pronouns VALUES('that');
INSERT INTO pronouns VALUES('their');
INSERT INTO pronouns VALUES('theirs');
INSERT INTO pronouns VALUES('them');
INSERT INTO pronouns VALUES('themselves');
INSERT INTO pronouns VALUES('these');
INSERT INTO pronouns VALUES('they');
INSERT INTO pronouns VALUES('this');
INSERT INTO pronouns VALUES('those');
INSERT INTO pronouns VALUES('us');
INSERT INTO pronouns VALUES('we');
INSERT INTO pronouns VALUES('what');
INSERT INTO pronouns VALUES('whatever');
INSERT INTO pronouns VALUES('which');
INSERT INTO pronouns VALUES('whichever');
INSERT INTO pronouns VALUES('who');
INSERT INTO pronouns VALUES('whoever');
INSERT INTO pronouns VALUES('whom');
INSERT INTO pronouns VALUES('whomever');
INSERT INTO pronouns VALUES('whose');
INSERT INTO pronouns VALUES('you');
INSERT INTO pronouns VALUES('your');
INSERT INTO pronouns VALUES('yours');
INSERT INTO pronouns VALUES('yourself');
INSERT INTO pronouns VALUES('yourselves');
