#!/usr/bin/python3
import sys
import cgi
def GET():
	sys.path.append('../')
	import interfaces
	form = cgi.FieldStorage()
	print("Content-type:text/json\r\n\r\n")
	if 'newsid' not in form:
		print('{ "error": "Please fill in newsid field." }')
		return
	else:
		newsid = str(form['newsid'].value)
		interfaces.Twitter(newsid).print_json_response()
		
GET()
