#!/usr/bin/python3
__author__ = 'jamin'
import sys
import cgi
def GET():
    sys.path.append('../')
    import interfaces
    form = cgi.FieldStorage()
    print("Content-type:text/json\r\n\r\n")
    hours = 0
    if 'days' not in form \
            and'hours' not in form\
            and 'minutes' not in form:
	    print('{ "error": "Please fill in days/hours/minutes field." }')
    else:
        d = form['days'].value
        h = form['hours'].value
        m = form['minutes'].value

    interfaces.Correlate(days=d, hours=h, minutes=m).print_json_response()

GET()
