#!/usr/bin/python3
import sys
import cgi
def GET():
	sys.path.append('../')
	import interfaces
	form = cgi.FieldStorage()
	print("Content-type:text/json\r\n\r\n")
	mindate = str('2015-02-11 00:00:00')
	interfaces.Feedzilla(mindate).print_json_response()
		
GET()
